### ISSUE TITLE
Extension is not working on Windows

### ISSUE THREAD

**Issue by Luismcplopes** [ceyhunkeklik/vscode-ngrok-client#1]
Hi there,
This is a great idea.
Do you tested on windows system? I have try it on windows but dont work :(
If i have time i will try to test on Linux and on Mac.
If you cold add a way to config the authtoken for register users from ngrok and a way to configur the port it was really fantastic.
Thanks

**Comment by ceyhunkeklik** [comment]
Hi @Luismcplopes,
Thanks for your feedback/report. You're right. The extension has an issue on Windows. I'll fix it ASAP.
